name: Docker Deploy

on:
  push:
    branches:
      - main # Срабатывает при пуше в ветку main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      # Проверяем репозиторий
      - name: Checkout code
        uses: actions/checkout@v3

      # Настраиваем Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Логинимся в Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Собираем и пушим образ в Docker Hub
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/energy-charts-bot:latest
          build-args: |
            TOKEN=${{ secrets.TOKEN }}
            WEB_APP_URL=${{ secrets.WEB_APP_URL }}
            SERVER_URL=${{ secrets.SERVER_URL }}
            PORT=${{ secrets.PORT }}